apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db-monitor
  name: db-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-monitor
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: db-monitor
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - image: kapte1/dockertest:dbmonitor
      imagePullPolicy: Always
        name: db-monitor
        env:
        - name: DB_TYPE
          value: my
        - name: DB_HOST
          value: "10.0.91.86"
        - name: DB_PASSWORD
          value: "passw0rd"
        - name: DB_USER
          value: "new_user"
        - name: DB_DATABASE
          value: "db_monitor"
        - name: REDIS_CREDS
          value: "10.244.0.41:6379:fP9d0QTUWw"
---
apiVersion: v1
kind: Service
metadata:
  name: db-monitor-entrypoint
spec:
  type: LoadBalancer
  selector:
    app: db-monitor
  ports:
  - port: 8080
    targetPort: 8080
