apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: tkgs-kirti-cluster1
  namespace: test-tmc
spec:
  distribution:
    version: v1.20.2+vmware.1-tkg.2.3e10706
  topology:
    controlPlane:
      count: 1
      class: best-effort-small
      storageClass: tanzu
    workers:
      count: 3
      class: best-effort-small
      storageClass: tanzu
