apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gitwriter-sc
  labels:
    app.kubernetes.io/part-of: hello-world
    carto.run/workload-name: gitwriter-sc
    app.kubernetes.io/component: run
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - name: workload
        image: harbor.fbclouddemo.us/tap-packages/example-gitwriter-sc-gitwriter-sc@sha256:a5a8d7f578f5d25c0b0deebfc523dd26e5fcff9709d84654e59e3f16277589e4
        securityContext:
          runAsUser: 1000
      imagePullSecrets:
      - name: registry-credentials

