apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gitwriter-sc
  labels:
    app.kubernetes.io/part-of: hello-world
    carto.run/workload-name: gitwriter-sc
    app.kubernetes.io/component: run
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - name: workload
        image: harbor.fbclouddemo.us/tap-packages/example-gitwriter-sc-gitwriter-sc@sha256:96e29896007f25a8a3f1fc0cc73ea42b3577c6ca0cb47307280305a522ce38fd
        securityContext:
          runAsUser: 1000
      imagePullSecrets:
      - name: registry-credentials

